#cloud-config
package_upgrade: true
package_update: true

packages:
  - wget
  - git
  - mc
  - ntp
  - python-pip
  - python-boto
  - fail2ban

runcmd:
  - sed -i -e 's/#Port 22/Port 443/g' /etc/ssh/sshd_config
  - systemctl restart sshd
  - pip install -U pip
  - pip install -U pyOpenSSL
  - pip install -U ansible
  - pip install -U awscli


