#cloud-config
package_upgrade: true
package_update: true

packages:
  - wget
  - git
  - mc
  - ntp
  - python-pip
  - python-boto
  - fail2ban

runcmd:
  - pip install -U pip
  - pip install -U pyOpenSSL==17.3.0
  - pip install -U ansible==2.4.0
  - pip install -U awscli


