#cloud-config
package_upgrade: true
package_update: true

packages:
  - wget
  - git
  - mc
  - ntp
  - python3-pip
  - python3-boto
  - fail2ban

write_files:
  - path: /etc/yum.repos.d/ganesha.repo
    content: |
      [lizardfs-deps]
      name=LizardFS Dependency Packages
      baseurl=http://packages.lizardfs.com/yum/el7-deps/
      enabled=1
      gpgcheck=0
      gpgkey=

runcmd:
  - sed -i -e 's/#Port 22/Port 443/g' /etc/ssh/sshd_config
  - sed -i -e 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
  - pip3 install -U awscli
  - shutdown -r now



