#cloud-config
package_upgrade: true
package_update: true

packages:
  - wget
  - git
  - mc
  - ntp
  - python3-pip
  - python3-boto
  - fail2ban

runcmd:
  - sed -i -e 's/Port 22/Port 443/g' /etc/ssh/sshd_config
  - systemctl restart sshd
  - echo "auto eth1" >> /etc/network/interfaces.d/50-cloud-init.cfg
  - echo "iface eth1 inet dhcp" >> /etc/network/interfaces.d/50-cloud-init.cfg
  - systemctl restart networking
  - pip3 install -U awscli

