- hosts: internet
  become: true

  tasks:
    - name: Registering instance metadata to ansible facts
      ec2_metadata_facts:

    - name: Lets create /dev/xvdx partition if it not exsiting.
      parted:
        device: /dev/xvdx
        number: 1
        state: present

    - name: Lets create FS on disk /dev/xvdx
      filesystem:
        fstype: xfs
        dev: /dev/xvdx1

    - name: Lets create directory for mount
      file:
        path: "/glusterfs"
        state: directory

    - name: Lets create mount point in fstab and mount our disk (/dev/xvdx1)
      mount:
        path: "/glusterfs"
        src: /dev/xvdx1
        fstype: xfs
        opts: rw
        state: mounted


    - name: lets remove nfs kernel server related stuff
      yum:
        name: ['ctdb', 'nfs-common', 'nfs-kernel-server']
        state: absent

#    - apt_repository:
#       filename: glusterfs
#       repo: 'ppa:gluster/glusterfs-6'



    - name: Installing GlusterFS repo
      yum:
        name: ['centos-release-gluster6']
        state: latest

    - name: Installing GlusterFS from repository
      yum:
        name: ['centos-release-gluster6', 'xfsprogs', 'attr', 'glusterfs', 'glusterfs-api', 'glusterfs-cli', 'glusterfs-fuse', 'glusterfs-server']
        state: latest


    - name: Lets make sure GlusterFS is starting after restart
      service:
        name: glusterd
        state: started
        enabled: true

    - name: Lets create directory for brick
      file:
        path: "/glusterfs/brick"
        state: directory

    - name: probe gluster nodes
      shell: "gluster peer probe  {{ item }}  >> /tmp/log.gluster.cluster"
      with_items: '{{ groups.public }}'
      run_once: true

    - name: create gluster volume with 1 arbiter (server3) and 2 data nodes (server1 and server2)
      gluster_volume:
        state: "present"
        volume: "nfs"
        bricks: "/glusterfs/brick"
        cluster:
          - server1-pub.virtyhost.com
          - server2-pub.virtyhost.com
          - server3-pub.virtyhost.com
        replicas: 3
      run_once: true

#    - name: mkdir for gluster-client share
#      file:
#        path: /nfs
#        state: directory

#    - name: mount the /NFS from Volume from glusterfs
#      shell: "mount -t glusterfs localhost:/nfs /nfs"

